### ISSUE TITLE
Releases should be versioned

### ISSUE THREAD

**Issue by drywheat** [royrusso/elasticsearch-HQ#169]
I like this plugin and I would like to use it in production but it's impossible to trust that a provisioning run ( using Chef ) sometime in the future will not break on install.

It's trivial to version this project using github and that should provide peace of mind to many.

**Comment by juretta** [comment]
+1 for this. I've created a snapshot of master so that we can get deterministic deployments. Ideally the plugin would follow the http://semver.org/ strategy, tagging the versions in source. This would be sufficient to provide versioned releases on https://github.com/royrusso/elasticsearch-HQ/releases.

**Comment by royrusso** [comment]
I've adopted semantic versioning. With the release of ES 2.x, two main branches are maintained now.
